default:
  before_script:
    - env

# .retry-and-timeout: &retry-and-timeout
#   retry: 1
#   timeout: 15 minutes

stages:
  - unit
  - e2e
  - status

# ACCESS

include:
  - local: .gitlab/ci/access/main.yml
