variables:
  # GIT_STRATEGY: clone
  GIT_CLEAN_FLAGS: -ffdx
  RUNNER_SCRIPT_TIMEOUT: 1h55m
  RUNNER_AFTER_SCRIPT_TIMEOUT: 5m

default:
  before_script:
    - env

stages:
  - unit
  - e2e
  - status

include:
  - local: .gitlab/ci/resources/anvil.yml
  - local: .gitlab/ci/resources/expanse.yml
  - local: .gitlab/ci/resources/bridges2.yml
  - local: .gitlab/ci/resources/delta.yml
  # - local: .gitlab/ci/resources/delta-ai.yml
  - local: .gitlab/ci/resources/jetstream.yml
  - local: .gitlab/ci/resources/stampede3.yml
  # - local: .gitlab/ci/resources/path-ospool.yml
  # - local: .gitlab/ci/resources/nrp.yml
  # - local: .gitlab/ci/resources/chameleon.yml
  # - local: .gitlab/ci/resources/fabric.yml
